"""Demo/mock university dataset (clearly sample data)."""

from __future__ import annotations

MOCK_UNIVERSITIES: list[dict] = [
    {
        "id": "cmu",
        "name": "Carnegie Mellon University",
        "country": "United States",
        "country_code": "US",
        "state": "Pennsylvania",
        "city": "Pittsburgh",
        "website": "https://www.cmu.edu",
        "domains": ["cmu.edu"],
        "programs": [
            {"id": "cs-bs", "name": "Computer Science", "level": "bachelor", "department": "SCS"},
            {"id": "ece-ms", "name": "Electrical and Computer Engineering", "level": "master", "department": "ECE"},
            {"id": "mld-phd", "name": "Machine Learning", "level": "phd", "department": "MLD"},
        ],
    },
    {
        "id": "mit",
        "name": "Massachusetts Institute of Technology",
        "country": "United States",
        "country_code": "US",
        "state": "Massachusetts",
        "city": "Cambridge",
        "website": "https://www.mit.edu",
        "domains": ["mit.edu"],
        "programs": [
            {"id": "ee-bs", "name": "Electrical Engineering", "level": "bachelor", "department": "EECS"},
        ],
    },
    {
        "id": "stanford",
        "name": "Stanford University",
        "country": "United States",
        "country_code": "US",
        "state": "California",
        "city": "Stanford",
        "website": "https://www.stanford.edu",
        "domains": ["stanford.edu"],
        "programs": [],
    },
    {
        "id": "oxford",
        "name": "University of Oxford",
        "country": "United Kingdom",
        "country_code": "GB",
        "state": None,
        "city": "Oxford",
        "website": "https://www.ox.ac.uk",
        "domains": ["ox.ac.uk"],
        "programs": [],
    },
    {
        "id": "toronto",
        "name": "University of Toronto",
        "country": "Canada",
        "country_code": "CA",
        "state": "Ontario",
        "city": "Toronto",
        "website": "https://www.utoronto.ca",
        "domains": ["utoronto.ca"],
        "programs": [],
    },
    {
        "id": "iitb",
        "name": "Indian Institute of Technology Bombay",
        "country": "India",
        "country_code": "IN",
        "state": "Maharashtra",
        "city": "Mumbai",
        "website": "https://www.iitb.ac.in",
        "domains": ["iitb.ac.in"],
        "programs": [],
    },
    {
        "id": "tum",
        "name": "Technical University of Munich",
        "country": "Germany",
        "country_code": "DE",
        "state": "Bavaria",
        "city": "Munich",
        "website": "https://www.tum.de",
        "domains": ["tum.de"],
        "programs": [],
    },
    {
        "id": "nus",
        "name": "National University of Singapore",
        "country": "Singapore",
        "country_code": "SG",
        "state": None,
        "city": "Singapore",
        "website": "https://www.nus.edu.sg",
        "domains": ["nus.edu.sg"],
        "programs": [],
    },
    {
        "id": "anu",
        "name": "Australian National University",
        "country": "Australia",
        "country_code": "AU",
        "state": "ACT",
        "city": "Canberra",
        "website": "https://www.anu.edu.au",
        "domains": ["anu.edu.au"],
        "programs": [],
    },
    {
        "id": "usp",
        "name": "University of São Paulo",
        "country": "Brazil",
        "country_code": "BR",
        "state": "São Paulo",
        "city": "São Paulo",
        "website": "https://www.usp.br",
        "domains": ["usp.br"],
        "programs": [],
    },
]
